name: Deploy API to Azure Container Apps

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/api-deploy.yml'

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_RESOURCE_GROUP: fce-demo-rg
  AZURE_CONTAINERAPP_NAME: fce-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login to ACR
        run: echo "${ACR_PASSWORD}" | docker login "${ACR_LOGIN_SERVER}" -u "${ACR_USERNAME}" --password-stdin

      - name: Build and push backend image
        run: |
          docker build -f backend/Dockerfile -t ${ACR_LOGIN_SERVER}/fce-backend:${{ github.sha }} -t ${ACR_LOGIN_SERVER}/fce-backend:latest .
          docker push ${ACR_LOGIN_SERVER}/fce-backend:${{ github.sha }}
          docker push ${ACR_LOGIN_SERVER}/fce-backend:latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        run: |
          az extension add --name containerapp --upgrade
          az account set --subscription "$AZURE_SUBSCRIPTION_ID"
          az containerapp update -n "$AZURE_CONTAINERAPP_NAME" -g "$AZURE_RESOURCE_GROUP" --image ${ACR_LOGIN_SERVER}/fce-backend:${{ github.sha }}


